"""Utility for rendering PPTX files."""

import os
from typing import Any
from pptx import Presentation
from pptx.util import Inches, Pt

def create_deck(title: str, slides: list[dict[str, Any]], output_path: str):
    """
    Create a PPTX deck.
    slides: list of { "title": str, "content": str, "points": list[str] }
    """
    prs = Presentation()
    
    # Title slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title_shape = slide.shapes.title
    subtitle_shape = slide.placeholders[1]
    title_shape.text = title
    subtitle_shape.text = "Generated by DeepTutor"

    # Content slides
    for s_data in slides:
        slide_layout = prs.slide_layouts[1] # Title and Content
        slide = prs.slides.add_slide(slide_layout)
        
        shapes = slide.shapes
        title_shape = shapes.title
        body_shape = shapes.placeholders[1]
        
        title_shape.text = s_data.get("title", "Slide")
        
        tf = body_shape.text_frame
        tf.text = s_data.get("content", "")
        
        for point in s_data.get("points", []):
            p = tf.add_paragraph()
            p.text = point
            p.level = 1

    prs.save(output_path)
    return output_path
